### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by MAX1MDEV** [Cr0mb/CS2-Cheat-Python#2]
How to switch wh?

**Comment by MAX1MDEV** [comment]
How to open gui?

**Comment by Cr0mb** [comment]
is external there is not button to open GUI, should open immediately with options to enabled / disable all features. if not working for you, or if black screen shows, then you did not have all necessary modules installed.

**Comment by MAX1MDEV** [comment]
> is external there is not button to open GUI, should open immediately with options to enabled / disable all features. if not working for you, or if black screen shows, then you did not have all necessary modules installed.

in the last version you could open the menu, so don't write nonsense ;) Externalal cheat on tkinter, the menu is easy to make.
