### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by j621103** [Cr0mb/CS2-Cheat-Python#4]
Can you help me convert it to an executable file?  ( .exe ) 
I can’t convert because it’s too difficult
tks

**Comment by MAX1MDEV** [comment]
bro, just use auto-py-to-exe
its very simple

**Comment by j621103** [comment]
> bro, just use auto-py-to-exe its very simple

![IMG_7203](https://github.com/Cr0mb/CS2-Cheat-Python/assets/130594594/14dfe2fa-993d-445f-829b-234923ff8763)
I installed it successfully (auto-py-to-exe)
The executable file was also successfully exported  (GHax.exe)
Execute with administrator rights (GHax.exe)
It keeps crashing

**Comment by j621103** [comment]
problem has been solved
tks
